name: CI - Frontend
run-name: "CI: Build frontend"

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/*frontend*.yml'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  backend-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build frontend
        run: docker compose build frontend